/* =========================================================
   RESET – kør i denne rækkefølge pga. FK
========================================================= */
DELETE FROM SHOWS;
DELETE FROM PROGRAMS;
DELETE FROM THEATERS;
DELETE FROM MOVIES;

/* =========================================================
   THEATERS
========================================================= */
INSERT INTO THEATERS (NAME, ROW_COUNT, SEAT_COUNT) VALUES ('Theater 1', 20, 12);
INSERT INTO THEATERS (NAME, ROW_COUNT, SEAT_COUNT) VALUES ('Theater 2', 25, 16);
INSERT INTO THEATERS (NAME, ROW_COUNT, SEAT_COUNT) VALUES ('Theater 3', 18, 14);

/* =========================================================
   MOVIES
========================================================= */
INSERT INTO MOVIES (TITLE, CATEGORY, AGE_LIMIT, RUN_TIME, RELEASE_YEAR, LANGUAGE)
VALUES ('Oppenheimer',       'Drama',     15, 180, 2023, 'English');

INSERT INTO MOVIES (TITLE, CATEGORY, AGE_LIMIT, RUN_TIME, RELEASE_YEAR, LANGUAGE)
VALUES ('Dune: Part Two',    'Sci-Fi',    12, 165, 2024, 'English');

INSERT INTO MOVIES (TITLE, CATEGORY, AGE_LIMIT, RUN_TIME, RELEASE_YEAR, LANGUAGE)
VALUES ('Inside Out 2',      'Animation',  7, 100, 2024, 'English');

INSERT INTO MOVIES (TITLE, CATEGORY, AGE_LIMIT, RUN_TIME, RELEASE_YEAR, LANGUAGE)
VALUES ('Aurora',            'Sci-Fi',    11, 125, 2025, 'English');

INSERT INTO MOVIES (TITLE, CATEGORY, AGE_LIMIT, RUN_TIME, RELEASE_YEAR, LANGUAGE)
VALUES ('Winter Tales',      'Family',     7, 105, 2025, 'English');

INSERT INTO MOVIES (TITLE, CATEGORY, AGE_LIMIT, RUN_TIME, RELEASE_YEAR, LANGUAGE)
VALUES ('Midnight Express',  'Thriller',  15, 118, 2025, 'English');

INSERT INTO MOVIES (TITLE, CATEGORY, AGE_LIMIT, RUN_TIME, RELEASE_YEAR, LANGUAGE)
VALUES ('Avengers: Secret Wars', 'Action', 13, 145, 2026, 'English');

/* =========================================================
   PROGRAMS – (film x sal x måned)
   Vi holder os til okt/nov/dec 2025
========================================================= */

-- OCT 2025
INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2025-10-01', DATE '2025-10-31'
FROM MOVIES m JOIN THEATERS t ON t.NAME='Theater 1'
WHERE m.TITLE='Oppenheimer';

INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2025-10-01', DATE '2025-10-31'
FROM MOVIES m JOIN THEATERS t ON t.NAME='Theater 2'
WHERE m.TITLE='Dune: Part Two';

INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2025-10-01', DATE '2025-10-31'
FROM MOVIES m JOIN THEATERS t ON t.NAME='Theater 3'
WHERE m.TITLE='Inside Out 2';

INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2025-10-01', DATE '2025-10-31'
FROM MOVIES m JOIN THEATERS t ON t.NAME='Theater 3'
WHERE m.TITLE='Avengers: Secret Wars';

-- NOV 2025
INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2025-11-01', DATE '2025-11-30'
FROM MOVIES m JOIN THEATERS t ON t.NAME='Theater 1'
WHERE m.TITLE='Oppenheimer';

INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2025-11-01', DATE '2025-11-30'
FROM MOVIES m JOIN THEATERS t ON t.NAME='Theater 2'
WHERE m.TITLE='Dune: Part Two';

INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2025-11-01', DATE '2025-11-30'
FROM MOVIES m JOIN THEATERS t ON t.NAME='Theater 1'
WHERE m.TITLE='Inside Out 2';

INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2025-11-01', DATE '2025-11-30'
FROM MOVIES m JOIN THEATERS t ON t.NAME='Theater 3'
WHERE m.TITLE='Avengers: Secret Wars';

-- DEC 2025
INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2025-12-01', DATE '2025-12-31'
FROM MOVIES m JOIN THEATERS t ON t.NAME='Theater 1'
WHERE m.TITLE='Oppenheimer';

INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2025-12-01', DATE '2025-12-31'
FROM MOVIES m JOIN THEATERS t ON t.NAME='Theater 2'
WHERE m.TITLE='Dune: Part Two';

INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2025-12-01', DATE '2025-12-31'
FROM MOVIES m JOIN THEATERS t ON t.NAME='Theater 1'
WHERE m.TITLE='Inside Out 2';

INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2025-12-01', DATE '2025-12-31'
FROM MOVIES m JOIN THEATERS t ON t.NAME='Theater 3'
WHERE m.TITLE='Avengers: Secret Wars';

/* =========================================================
   SHOWS – 2 pr. film pr. måned + ekstra “same-day” blokke
   (ingen overlap i samme sal)
========================================================= */

-- ========== OCT ==========
-- Oppenheimer (Th1)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-05 16:30:00', TIMESTAMP '2025-10-05 19:30:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Oppenheimer' AND th.NAME='Theater 1' AND p.START_DATE=DATE '2025-10-01';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-20 20:00:00', TIMESTAMP '2025-10-20 23:00:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Oppenheimer' AND th.NAME='Theater 1' AND p.START_DATE=DATE '2025-10-01';

-- Dune (Th2)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-08 19:00:00', TIMESTAMP '2025-10-08 21:45:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Dune: Part Two' AND th.NAME='Theater 2' AND p.START_DATE=DATE '2025-10-01';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-22 17:30:00', TIMESTAMP '2025-10-22 20:15:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Dune: Part Two' AND th.NAME='Theater 2' AND p.START_DATE=DATE '2025-10-01';

-- Inside Out 2 (Th3, dag)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-05 13:00:00', TIMESTAMP '2025-10-05 14:40:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Inside Out 2' AND th.NAME='Theater 3' AND p.START_DATE=DATE '2025-10-01';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-25 14:00:00', TIMESTAMP '2025-10-25 15:40:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Inside Out 2' AND th.NAME='Theater 3' AND p.START_DATE=DATE '2025-10-01';

-- Avengers (Th3 – andre dage end IO2)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-15 19:30:00', TIMESTAMP '2025-10-15 22:05:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Avengers: Secret Wars' AND th.NAME='Theater 3' AND p.START_DATE=DATE '2025-10-01';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-29 19:30:00', TIMESTAMP '2025-10-29 22:05:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Avengers: Secret Wars' AND th.NAME='Theater 3' AND p.START_DATE=DATE '2025-10-01';

-- SAME-DAY 15/10 (IO2->Opp i Th1, Dune i Th2, Avengers i Th3) – ingen overlap pr. sal
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-15 13:00:00', TIMESTAMP '2025-10-15 14:40:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON th.THEATER_ID=p.THEATER_ID
WHERE p.START_DATE=DATE '2025-10-01' AND m.TITLE='Inside Out 2' AND th.NAME='Theater 1';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-15 17:00:00', TIMESTAMP '2025-10-15 20:00:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON th.THEATER_ID=p.THEATER_ID
WHERE p.START_DATE=DATE '2025-10-01' AND m.TITLE='Oppenheimer' AND th.NAME='Theater 1';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-15 19:00:00', TIMESTAMP '2025-10-15 21:45:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON th.THEATER_ID=p.THEATER_ID
WHERE p.START_DATE=DATE '2025-10-01' AND m.TITLE='Dune: Part Two' AND th.NAME='Theater 2';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-15 19:30:00', TIMESTAMP '2025-10-15 22:05:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON th.THEATER_ID=p.THEATER_ID
WHERE p.START_DATE=DATE '2025-10-01' AND m.TITLE='Avengers: Secret Wars' AND th.NAME='Theater 3';

-- SAME-DAY 22/10 (Opp i Th1, Dune i Th2, IO2+Avengers i Th3)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-22 20:15:00', TIMESTAMP '2025-10-22 23:15:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON th.THEATER_ID=p.THEATER_ID
WHERE p.START_DATE=DATE '2025-10-01' AND m.TITLE='Oppenheimer' AND th.NAME='Theater 1';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-22 16:30:00', TIMESTAMP '2025-10-22 19:15:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON th.THEATER_ID=p.THEATER_ID
WHERE p.START_DATE=DATE '2025-10-01' AND m.TITLE='Dune: Part Two' AND th.NAME='Theater 2';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-22 13:00:00', TIMESTAMP '2025-10-22 14:40:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON th.THEATER_ID=p.THEATER_ID
WHERE p.START_DATE=DATE '2025-10-01' AND m.TITLE='Inside Out 2' AND th.NAME='Theater 3';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-22 19:45:00', TIMESTAMP '2025-10-22 22:20:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON th.THEATER_ID=p.THEATER_ID
WHERE p.START_DATE=DATE '2025-10-01' AND m.TITLE='Avengers: Secret Wars' AND th.NAME='Theater 3';


-- ========== NOV ==========
-- Oppenheimer (Th1)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-11-12 20:00:00', TIMESTAMP '2025-11-12 23:00:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Oppenheimer' AND th.NAME='Theater 1' AND p.START_DATE=DATE '2025-11-01';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-11-28 17:30:00', TIMESTAMP '2025-11-28 20:30:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Oppenheimer' AND th.NAME='Theater 1' AND p.START_DATE=DATE '2025-11-01';

-- Dune (Th2)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-11-05 19:00:00', TIMESTAMP '2025-11-05 21:45:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Dune: Part Two' AND th.NAME='Theater 2' AND p.START_DATE=DATE '2025-11-01';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-11-15 17:00:00', TIMESTAMP '2025-11-15 19:45:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Dune: Part Two' AND th.NAME='Theater 2' AND p.START_DATE=DATE '2025-11-01';

-- Inside Out 2 (Th1, dag)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-11-10 15:00:00', TIMESTAMP '2025-11-10 16:40:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Inside Out 2' AND th.NAME='Theater 1' AND p.START_DATE=DATE '2025-11-01';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-11-24 13:30:00', TIMESTAMP '2025-11-24 15:10:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Inside Out 2' AND th.NAME='Theater 1' AND p.START_DATE=DATE '2025-11-01';

-- Avengers (Th3)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-11-21 19:30:00', TIMESTAMP '2025-11-21 22:05:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Avengers: Secret Wars' AND th.NAME='Theater 3' AND p.START_DATE=DATE '2025-11-01';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-11-29 18:30:00', TIMESTAMP '2025-11-29 21:05:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Avengers: Secret Wars' AND th.NAME='Theater 3' AND p.START_DATE=DATE '2025-11-01';

-- SAME-DAY 12/11 (IO2 dag i Th1, Dune i Th2, Opp i Th1 aften, Avengers Th3)
-- (IO2 ligger i Th1 i nov i dette datasæt)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-11-12 13:00:00', TIMESTAMP '2025-11-12 14:40:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON th.THEATER_ID=p.THEATER_ID
WHERE p.START_DATE=DATE '2025-11-01' AND m.TITLE='Inside Out 2' AND th.NAME='Theater 1';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-11-12 19:00:00', TIMESTAMP '2025-11-12 21:45:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON th.THEATER_ID=p.THEATER_ID
WHERE p.START_DATE=DATE '2025-11-01' AND m.TITLE='Dune: Part Two' AND th.NAME='Theater 2';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-11-12 20:00:00', TIMESTAMP '2025-11-12 23:00:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON th.THEATER_ID=p.THEATER_ID
WHERE p.START_DATE=DATE '2025-11-01' AND m.TITLE='Oppenheimer' AND th.NAME='Theater 1';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-11-12 19:30:00', TIMESTAMP '2025-11-12 22:05:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON th.THEATER_ID=p.THEATER_ID
WHERE p.START_DATE=DATE '2025-11-01' AND m.TITLE='Avengers: Secret Wars' AND th.NAME='Theater 3';


-- ========== DEC ==========
-- Oppenheimer (Th1)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-12-12 20:00:00', TIMESTAMP '2025-12-12 23:00:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Oppenheimer' AND th.NAME='Theater 1' AND p.START_DATE=DATE '2025-12-01';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-12-20 16:30:00', TIMESTAMP '2025-12-20 19:30:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Oppenheimer' AND th.NAME='Theater 1' AND p.START_DATE=DATE '2025-12-01';

-- Dune (Th2)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-12-05 19:30:00', TIMESTAMP '2025-12-05 22:15:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Dune: Part Two' AND th.NAME='Theater 2' AND p.START_DATE=DATE '2025-12-01';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-12-19 17:00:00', TIMESTAMP '2025-12-19 19:45:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Dune: Part Two' AND th.NAME='Theater 2' AND p.START_DATE=DATE '2025-12-01';

-- Inside Out 2 (Th1, dag)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-12-10 13:00:00', TIMESTAMP '2025-12-10 14:40:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Inside Out 2' AND th.NAME='Theater 1' AND p.START_DATE=DATE '2025-12-01';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-12-22 13:30:00', TIMESTAMP '2025-12-22 15:10:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Inside Out 2' AND th.NAME='Theater 1' AND p.START_DATE=DATE '2025-12-01';

-- Avengers (Th3)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-12-15 19:30:00', TIMESTAMP '2025-12-15 22:05:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Avengers: Secret Wars' AND th.NAME='Theater 3' AND p.START_DATE=DATE '2025-12-01';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-12-28 18:45:00', TIMESTAMP '2025-12-28 21:20:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Avengers: Secret Wars' AND th.NAME='Theater 3' AND p.START_DATE=DATE '2025-12-01';

/* =========================================================
   (Valgfrit) LEAP / DST edge-cases – kan bruges i senere tests
   -- Leap day eksempel:
   -- use TIMESTAMP '2028-02-29 18:00:00' ... på en valgfri PROGRAMS-række
   -- DST spring frem/fald tilbage kan testes med marts/okt tider
========================================================= */
