/* ---------------------------------------------------------
   Reset (kør i denne rækkefølge pga. foreign keys)
--------------------------------------------------------- */
DELETE FROM SHOWS;
DELETE FROM PROGRAMS;
DELETE FROM THEATERS;
DELETE FROM MOVIES;

/* ---------------------------------------------------------
   Theaters (sale)
--------------------------------------------------------- */
INSERT INTO THEATERS (NAME, ROW_COUNT, SEAT_COUNT) VALUES ('Theater 1', 20, 12);
INSERT INTO THEATERS (NAME, ROW_COUNT, SEAT_COUNT) VALUES ('Theater 2', 25, 16);

/* ---------------------------------------------------------
   Movies
   (tilpas feltnavne hvis dine kolonnenavne er anderledes)
--------------------------------------------------------- */
INSERT INTO MOVIES (TITLE, CATEGORY, AGE_LIMIT, RUN_TIME, RELEASE_YEAR, LANGUAGE)
VALUES ('Oppenheimer',       'Drama',     15, 180, 2023, 'English');

INSERT INTO MOVIES (TITLE, CATEGORY, AGE_LIMIT, RUN_TIME, RELEASE_YEAR, LANGUAGE)
VALUES ('Dune: Part Two',    'Sci-Fi',    12, 165, 2024, 'English');

INSERT INTO MOVIES (TITLE, CATEGORY, AGE_LIMIT, RUN_TIME, RELEASE_YEAR, LANGUAGE)
VALUES ('Inside Out 2',      'Animation',  7, 100, 2024, 'English');

INSERT INTO MOVIES (TITLE, CATEGORY, AGE_LIMIT, RUN_TIME, RELEASE_YEAR, LANGUAGE)
VALUES ('Aurora',            'Sci-Fi',    11, 125, 2025, 'English');

INSERT INTO MOVIES (TITLE, CATEGORY, AGE_LIMIT, RUN_TIME, RELEASE_YEAR, LANGUAGE)
VALUES ('Winter Tales',      'Family',     7, 105, 2025, 'English');

INSERT INTO MOVIES (TITLE, CATEGORY, AGE_LIMIT, RUN_TIME, RELEASE_YEAR, LANGUAGE)
VALUES ('Midnight Express',  'Thriller',  15, 118, 2025, 'English');

/* ---------------------------------------------------------
   Programs (binder Movie + Theater + plan-periode)
--------------------------------------------------------- */
-- Oppenheimer i oktober 2025 (Theater 1)
INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2025-10-01', DATE '2025-10-31'
FROM MOVIES m JOIN THEATERS t
                   ON m.TITLE='Oppenheimer' AND t.NAME='Theater 1';

-- Dune 2 i november 2025 (Theater 2)
INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2025-11-01', DATE '2025-11-30'
FROM MOVIES m JOIN THEATERS t
                   ON m.TITLE='Dune: Part Two' AND t.NAME='Theater 2';

-- Inside Out 2 i december 2025 (Theater 1)
INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2025-12-01', DATE '2025-12-31'
FROM MOVIES m JOIN THEATERS t
                   ON m.TITLE='Inside Out 2' AND t.NAME='Theater 1';

-- Aurora i november 2025 (Theater 2)
INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2025-11-01', DATE '2025-11-30'
FROM MOVIES m JOIN THEATERS t
                   ON m.TITLE='Aurora' AND t.NAME='Theater 2';

-- Winter Tales i december 2025 (Theater 1)
INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2025-12-01', DATE '2025-12-31'
FROM MOVIES m JOIN THEATERS t
                   ON m.TITLE='Winter Tales' AND t.NAME='Theater 1';

-- Midnight Express i januar 2026 (Theater 2)
INSERT INTO PROGRAMS (MOVIE_ID, THEATER_ID, START_DATE, END_DATE)
SELECT m.MOVIE_ID, t.THEATER_ID, DATE '2026-01-01', DATE '2026-01-31'
FROM MOVIES m JOIN THEATERS t
                   ON m.TITLE='Midnight Express' AND t.NAME='Theater 2';


/* ---------------------------------------------------------
   Shows (enkeltforestillinger) – med MOVIE_ID & THEATER_ID
   så NOT NULL + FK krav er opfyldt.
--------------------------------------------------------- */

-- Oppenheimer (oktober)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-14 20:00:00', TIMESTAMP '2025-10-14 23:00:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Oppenheimer' AND th.NAME='Theater 1';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-15 18:00:00', TIMESTAMP '2025-10-15 21:00:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Oppenheimer' AND th.NAME='Theater 1';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-10-20 16:30:00', TIMESTAMP '2025-10-20 19:30:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Oppenheimer' AND th.NAME='Theater 1';


-- Dune: Part Two (november)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-11-05 16:00:00', TIMESTAMP '2025-11-05 18:45:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Dune: Part Two' AND th.NAME='Theater 2';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-11-05 20:00:00', TIMESTAMP '2025-11-05 22:45:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Dune: Part Two' AND th.NAME='Theater 2';


-- Inside Out 2 (december)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-12-10 17:30:00', TIMESTAMP '2025-12-10 19:10:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Inside Out 2' AND th.NAME='Theater 1';


-- Aurora (november)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-11-08 19:00:00', TIMESTAMP '2025-11-08 21:05:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Aurora' AND th.NAME='Theater 2';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-11-15 19:30:00', TIMESTAMP '2025-11-15 21:35:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Aurora' AND th.NAME='Theater 2';


-- Winter Tales (december)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-12-05 16:00:00', TIMESTAMP '2025-12-05 17:45:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Winter Tales' AND th.NAME='Theater 1';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-12-12 18:00:00', TIMESTAMP '2025-12-12 19:45:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Winter Tales' AND th.NAME='Theater 1';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2025-12-22 14:00:00', TIMESTAMP '2025-12-22 15:45:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Winter Tales' AND th.NAME='Theater 1';


-- Midnight Express (januar 2026)
INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2026-01-04 20:00:00', TIMESTAMP '2026-01-04 22:00:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Midnight Express' AND th.NAME='Theater 2';

INSERT INTO SHOWS (PROGRAM_ID, MOVIE_ID, THEATER_ID, START_TIME, END_TIME)
SELECT p.PROGRAM_ID, p.MOVIE_ID, p.THEATER_ID,
       TIMESTAMP '2026-01-10 21:00:00', TIMESTAMP '2026-01-10 23:00:00'
FROM PROGRAMS p JOIN MOVIES m ON p.MOVIE_ID=m.MOVIE_ID JOIN THEATERS th ON p.THEATER_ID=th.THEATER_ID
WHERE m.TITLE='Midnight Express' AND th.NAME='Theater 2';


/* ---------------------------------------------------------
   Hurtige sanity checks (kører fint i H2; valgfrit)
--------------------------------------------------------- */
-- Antal shows pr. måned
-- SELECT COUNT(*) AS shows_oct FROM SHOWS WHERE START_TIME BETWEEN TIMESTAMP '2025-10-01 00:00:00' AND TIMESTAMP '2025-10-31 23:59:59';
-- SELECT COUNT(*) AS shows_nov FROM SHOWS WHERE START_TIME BETWEEN TIMESTAMP '2025-11-01 00:00:00' AND TIMESTAMP '2025-11-30 23:59:59';
-- SELECT COUNT(*) AS shows_dec FROM SHOWS WHERE START_TIME BETWEEN TIMESTAMP '2025-12-01 00:00:00' AND TIMESTAMP '2025-12-31 23:59:59';
-- SELECT COUNT(*) AS shows_jan FROM SHOWS WHERE START_TIME BETWEEN TIMESTAMP '2026-01-01 00:00:00' AND TIMESTAMP '2026-01-31 23:59:59';
